### ISSUE TITLE
How do you generate acorn-dynamic import

### ISSUE THREAD

**Issue by bastien-roucaries** [browserify/acorn-node#2]
Hi,

From debian side it is important to regenerate all stuff from source.

*How do you generate acorn-dynamic-import source ?

**Comment by goto-bus-stop** [comment]
I copy-pasted the source file because it wasn't yet published. acorn-dynamic-import has had a new release though so I'll update it in a moment, then it will be generated in the same way as the other dependencies.

**Comment by goto-bus-stop** [comment]
acorn-dynamic-import actually doesn't even need to be generated in the new version. Just published acorn-node v1.6.1 which depends on it directly!
