### ISSUE TITLE
Failed to install acorn-node@1.6.1

### ISSUE THREAD

**Issue by neotech-development** [browserify/acorn-node#4]
`npm install` error message:
```
...
npm ERR! node v6.12.0
npm ERR! npm  v2.15.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package acorn@5.7.3 does not satisfy its siblings' peerDependencies requirements!
...
```
It seems that updated dependency acorn-dynamic-import@4.0.0 requires acorn@6.0.2
But acorn-node@1.6.1 provides  acorn@^6.0.1

```
...
│ │ │   ├── https-browserify@1.0.0
│ │ │   ├─┬ insert-module-globals@7.2.0
│ │ │   │ ├─┬ acorn-node@1.6.1
│ │ │   │ │ ├── UNMET PEER DEPENDENCY acorn@6.0.2
│ │ │   │ │ ├── acorn-dynamic-import@4.0.0
│ │ │   │ │ └── acorn-walk@6.1.0
│ │ │   │ ├─┬ concat-stream@1.6.2
│ │ │   │ │ └── buffer-from@1.1.1
│ │ │   │ ├── is-buffer@1.1.6
...
```

**Comment by ljharb** [comment]
npm 2 is EOL anyways; on node 6 you should be using npm 3 at least (which i think is what it comes with).

**Comment by neotech-development** [comment]
npm@2 is used within cordova under the hood

**Comment by ljharb** [comment]
Still? Is there a tracking issue for them to update it?

**Comment by brodybits** [comment]
> npm@2 is used within cordova under the hood

Correct on Cordova 7, not correct on Cordova 8.

Cordova 8 uses the system-installed npm version, which should be at least npm@3.

**Comment by TerryCapan** [comment]
Currently running into a similar problem. Also commented here: https://github.com/kesne/acorn-dynamic-import/issues/18

```
│ ├─┬ insert-module-globals@7.2.0
│ │ ├─┬ acorn-node@1.6.2
│ │ │ ├── UNMET PEER DEPENDENCY acorn@6.0.4
│ │ │ ├── acorn-dynamic-import@4.0.0
│ │ │ ├── acorn-walk@6.1.1
│ │ │ └── xtend@4.0.1 deduped
```
